export const roleMeta = {
  staff: {
    label: "店员",
    persona: "周宁",
    store: "棱镜旗舰店",
    scope: "仅本店",
    defaultPage: "workbench",
    nav: [
      ["workbench", "工作台"],
      ["reservations", "预约"],
      ["orders", "商品订单"],
      ["repairs", "报修"],
      ["inventory", "库存"],
      ["shift", "班次与交接"],
    ],
  },
  manager: {
    label: "店长",
    persona: "许知远",
    store: "棱镜旗舰店",
    scope: "本店经营与配置",
    defaultPage: "store-dashboard",
    nav: [
      ["store-dashboard", "经营看板"],
      ["live-ops", "现场运营"],
      ["manager-inventory", "库存"],
      ["store-config", "门店配置"],
      ["people-schedule", "员工与排班"],
      ["store-audit", "审计与导出"],
    ],
  },
  hq: {
    label: "总部运营",
    persona: "沈微",
    store: "全部三店",
    scope: "跨店比较与配置",
    defaultPage: "chain-dashboard",
    nav: [
      ["chain-dashboard", "连锁看板"],
      ["store-compare", "门店比较"],
      ["chain-config", "连锁配置"],
      ["hq-store-config", "门店配置"],
      ["hq-people", "人员与排班"],
      ["hq-audit", "审计与导出"],
    ],
  },
};

export const reservations = [
  {
    id: "RSV-260808-00123",
    customer: "林澈",
    time: "19:30–21:30",
    arrival: "19:10–19:45",
    seat: "竞技区 A-18",
    profile: "竞技型",
    status: "已确认",
    amount: "¥30.00",
    note: "主演示预约",
  },
  {
    id: "RSV-260808-00131",
    customer: "陆远",
    time: "19:40–21:40",
    arrival: "19:20–19:55",
    seat: "竞技区 B-07",
    profile: "竞技型",
    status: "已确认",
    amount: "¥30.00",
    note: "到店窗口",
  },
  {
    id: "RSV-260808-00136",
    customer: "陈牧",
    time: "19:50–21:50",
    arrival: "19:30–20:05",
    seat: "竞技区 C-12",
    profile: "竞技型",
    status: "已确认",
    amount: "¥30.00",
    note: "到店窗口",
  },
  {
    id: "RSV-260808-00142",
    customer: "顾辰",
    time: "20:00–22:00",
    arrival: "19:40–20:15",
    seat: "竞技区 A-05",
    profile: "竞技型",
    status: "已确认",
    amount: "¥36.00",
    note: "即将开始",
  },
  {
    id: "RSV-260808-00097",
    customer: "周屿",
    time: "19:20–21:20",
    arrival: "19:00–19:35",
    seat: "竞技区 B-03",
    profile: "竞技型",
    status: "已到店",
    amount: "¥30.00",
    note: "等待开始",
  },
  {
    id: "RSV-260808-00091",
    customer: "许泽",
    time: "19:10–21:10",
    arrival: "18:50–19:25",
    seat: "竞技区 C-01",
    profile: "竞技型",
    status: "已到店",
    amount: "¥30.00",
    note: "等待开始",
  },
  {
    id: "RSV-260808-00072",
    customer: "莫子昂",
    time: "18:30–20:30",
    arrival: "18:10–18:45",
    seat: "竞技区 A-10",
    profile: "竞技型",
    status: "使用中",
    amount: "¥30.00",
    note: "设备异常",
  },
];

export const orders = [
  {
    id: "ORD-260808-0038",
    customer: "林澈",
    seat: "A-18",
    items: "能量饮料 ×1、薯片 ×1",
    total: "¥16.00",
    status: "已模拟支付",
    time: "19:18",
  },
  {
    id: "ORD-260808-0035",
    customer: "苏雨",
    seat: "C-12",
    items: "外设清洁套装 ×1",
    total: "¥18.00",
    status: "制作中",
    time: "19:05",
  },
  {
    id: "ORD-260808-0029",
    customer: "赵一航",
    seat: "B-07",
    items: "气泡水 ×2、泡面 ×1",
    total: "¥22.00",
    status: "待取",
    time: "18:44",
  },
  {
    id: "ORD-260808-0026",
    customer: "韩青",
    seat: "A-06",
    items: "低糖能量棒 ×2",
    total: "¥20.00",
    status: "已模拟支付",
    time: "18:37",
  },
  {
    id: "ORD-260808-0019",
    customer: "顾辰",
    seat: "D-03",
    items: "苏打水 ×1",
    total: "¥8.00",
    status: "已完成",
    time: "18:12",
  },
];

export const repairs = [
  {
    id: "RPR-260808-0017",
    issue: "耳机右声道无声",
    seat: "竞技区 A-18",
    profile: "竞技型",
    priority: "紧急",
    status: "待分派",
    assignee: "未分派",
    source: "顾客报修",
    opened: "19:20",
    customer: "林澈",
    publicNote: "门店已收到问题，正在安排处理。",
  },
  {
    id: "RPR-260808-0015",
    issue: "键盘部分按键失灵",
    seat: "竞技区 C-03",
    profile: "竞技型",
    priority: "较高",
    status: "已分派",
    assignee: "周宁",
    source: "店员创建",
    opened: "19:10",
    customer: "—",
    publicNote: "已安排人员检查。",
  },
  {
    id: "RPR-260808-0012",
    issue: "鼠标滚轮异常",
    seat: "竞技区 B-11",
    profile: "竞技型",
    priority: "普通",
    status: "待验证",
    assignee: "陈昊",
    source: "顾客报修",
    opened: "18:58",
    customer: "陆远",
    publicNote: "已更换鼠标，等待验证。",
  },
  {
    id: "RPR-260808-0009",
    issue: "显示线接触不良",
    seat: "旗舰区 F-06",
    profile: "旗舰型",
    priority: "普通",
    status: "处理中",
    assignee: "苏雨",
    source: "店员创建",
    opened: "18:42",
    customer: "—",
    publicNote: "正在更换显示线。",
  },
];

export const inventory = [
  {
    name: "能量饮料",
    type: "商品",
    book: 48,
    reserved: 6,
    available: 42,
    threshold: 12,
    state: "正常",
    updated: "19:18",
  },
  {
    name: "气泡水",
    type: "商品",
    book: 32,
    reserved: 4,
    available: 28,
    threshold: 10,
    state: "正常",
    updated: "18:44",
  },
  {
    name: "外设清洁套装",
    type: "商品",
    book: 9,
    reserved: 6,
    available: 3,
    threshold: 5,
    state: "低库存",
    updated: "19:05",
  },
  {
    name: "替换耳机",
    type: "备件",
    book: 4,
    reserved: 2,
    available: 2,
    threshold: 3,
    state: "低库存",
    updated: "18:55",
  },
  {
    name: "显示线",
    type: "备件",
    book: 6,
    reserved: 1,
    available: 5,
    threshold: 4,
    state: "正常",
    updated: "18:42",
  },
  {
    name: "鼠标滚轮组件",
    type: "备件",
    book: 3,
    reserved: 2,
    available: 1,
    threshold: 2,
    state: "低库存",
    updated: "18:58",
  },
];

export const storeMetrics = [
  {
    label: "模拟营业额",
    value: "¥18,640",
    delta: "+8.4%",
    tone: "cyan",
    detail: "预约 ¥15,920 · 商品 ¥2,720",
  },
  {
    label: "运营座位利用率",
    value: "84.2%",
    delta: "+3.1%",
    tone: "lime",
    detail: "使用分钟 / 正常可经营座位分钟",
  },
  {
    label: "维护不可用率",
    value: "3.8%",
    delta: "+0.6%",
    tone: "amber",
    detail: "维护分钟 / 营业座位分钟",
  },
  {
    label: "订单完成率",
    value: "92.6%",
    delta: "+1.8%",
    tone: "cyan",
    detail: "已完成 / 已进入终态且模拟支付",
  },
];

export const dailyTrend = [
  { day: "08/02", flagship: 72, standard: 58, newStore: 34 },
  { day: "08/03", flagship: 76, standard: 61, newStore: 38 },
  { day: "08/04", flagship: 68, standard: 55, newStore: 31 },
  { day: "08/05", flagship: 81, standard: 63, newStore: 39 },
  { day: "08/06", flagship: 79, standard: 66, newStore: 42 },
  { day: "08/07", flagship: 86, standard: 64, newStore: 40 },
  { day: "08/08", flagship: 84, standard: 62, newStore: 37 },
];

export const revenueTrend = [
  { time: "06:00", reservation: 520, product: 80 },
  { time: "09:00", reservation: 1180, product: 140 },
  { time: "12:00", reservation: 2450, product: 380 },
  { time: "15:00", reservation: 3160, product: 520 },
  { time: "18:00", reservation: 4720, product: 860 },
  { time: "21:00", reservation: 3890, product: 740 },
  { time: "次日00:00", reservation: 2160, product: 0 },
];

export const stores = [
  {
    name: "棱镜旗舰店",
    label: "旗舰店",
    seats: 96,
    hours: "24 小时",
    utilization: "84.2%",
    maintenance: "3.8%",
    revenue: "¥18,640",
    orders: "92.6%",
    alert: "报修待验证 1",
  },
  {
    name: "星桥标准店",
    label: "标准店",
    seats: 64,
    hours: "10:00–次日 02:00",
    utilization: "62.4%",
    maintenance: "1.6%",
    revenue: "¥10,820",
    orders: "94.1%",
    alert: "交接异常 1",
  },
  {
    name: "极点新店",
    label: "新店",
    seats: 40,
    hours: "12:00–24:00",
    utilization: "37.1%",
    maintenance: "6.2%",
    revenue: "¥5,260",
    orders: "88.3%",
    alert: "低库存 2 · 报修中 1",
  },
];

export const employees = [
  {
    code: "PRISM-S001",
    name: "周宁",
    role: "店员",
    status: "任职",
    store: "棱镜旗舰店 · 固定",
    shift: "18:00–02:00",
    attendance: "已模拟签到 18:02",
    handover: "待提交",
    protected: true,
  },
  {
    code: "PRISM-S002",
    name: "陈昊",
    role: "店员",
    status: "任职",
    store: "棱镜旗舰店 · 固定",
    shift: "17:30–01:30",
    attendance: "已模拟签到 17:24",
    handover: "正常",
    protected: false,
  },
  {
    code: "PRISM-S003",
    name: "苏雨",
    role: "店员",
    status: "任职",
    store: "棱镜旗舰店 · 固定",
    shift: "16:00–24:00",
    attendance: "迟到 16:12",
    handover: "正常",
    protected: false,
  },
  {
    code: "PRISM-M001",
    name: "许知远",
    role: "店长",
    status: "任职",
    store: "棱镜旗舰店 · 固定",
    shift: "14:00–22:00",
    attendance: "已模拟签到 13:55",
    handover: "—",
    protected: true,
  },
  {
    code: "PRISM-S004",
    name: "赵一航",
    role: "店员",
    status: "任职",
    store: "棱镜旗舰店 · 固定",
    shift: "22:00–次日06:00",
    attendance: "未到签到窗口",
    handover: "接班待确认",
    protected: false,
  },
];

export const auditEvents = [
  {
    time: "19:22:14",
    persona: "周宁",
    role: "店员",
    store: "棱镜旗舰店",
    action: "分派报修",
    object: "RPR-…0017",
    result: "允许",
    correlation: "req_7f…a2",
  },
  {
    time: "19:18:42",
    persona: "林澈",
    role: "顾客",
    store: "棱镜旗舰店",
    action: "商品订单模拟支付",
    object: "ORD-…0038",
    result: "允许",
    correlation: "req_9c…10",
  },
  {
    time: "19:12:05",
    persona: "系统",
    role: "系统",
    store: "棱镜旗舰店",
    action: "预约确认",
    object: "RSV-…0123",
    result: "允许",
    correlation: "req_1a…d4",
  },
  {
    time: "19:03:27",
    persona: "未知旧标签",
    role: "店员",
    store: "棱镜旗舰店",
    action: "开始使用",
    object: "RSV-…0091",
    result: "拒绝",
    correlation: "req_b3…19",
  },
  {
    time: "18:58:33",
    persona: "陈昊",
    role: "店员",
    store: "棱镜旗舰店",
    action: "提交解决说明",
    object: "RPR-…0012",
    result: "允许",
    correlation: "req_45…cc",
  },
  {
    time: "18:42:09",
    persona: "苏雨",
    role: "店员",
    store: "棱镜旗舰店",
    action: "领用备件",
    object: "INV-…0046",
    result: "允许",
    correlation: "req_f2…08",
  },
];

export const pricePlans = [
  {
    id: "competitive-base-v2",
    storeArea: "棱镜旗舰店 · 竞技区 A",
    profile: "竞技型",
    time: "06:00–18:00",
    weekdayPrice: "¥7.50",
    weekendPrice: "¥8.63",
    effective: "2026-08-11 11:00 起",
    version: "v2 · 未来",
  },
  {
    id: "competitive-base-v1",
    storeArea: "棱镜旗舰店 · 竞技区 A",
    profile: "竞技型",
    time: "06:00–18:00",
    weekdayPrice: "¥7.50",
    weekendPrice: "¥8.63",
    effective: "2026-07-28 10:29–08-11 11:00",
    version: "v1 · 当前",
  },
  {
    id: "competitive-evening-v1",
    storeArea: "棱镜旗舰店 · 竞技区 A",
    profile: "竞技型",
    time: "18:00–次日00:00",
    weekdayPrice: "¥9.00",
    weekendPrice: "¥8.63",
    effective: "2026-07-28 10:29 起",
    version: "v1 · 当前",
  },
  {
    id: "competitive-overnight-v1",
    storeArea: "棱镜旗舰店 · 竞技区 A",
    profile: "竞技型",
    time: "00:00–06:00",
    weekdayPrice: "¥6.75",
    weekendPrice: "¥8.63",
    effective: "2026-07-28 10:29 起",
    version: "v1 · 当前",
  },
];

export const demoSteps = [
  {
    role: "顾客",
    object: "棱镜旗舰店即时预约",
    action: "创建即时两小时预约",
    entry: "顾客 H5 · 预约首页",
    completion: "竞技型、两小时、立即开始且使用预约体验券的主预约已创建。",
    nextAction: "前往顾客 H5 创建预约",
  },
  {
    role: "顾客",
    object: "主预约模拟支付",
    action: "确认预约模拟支付",
    entry: "顾客 H5 · 我的预约",
    completion: "主预约已模拟支付并进入已确认；不会产生真实扣款。",
    nextAction: "模拟支付该预约",
  },
  {
    role: "店员",
    object: "主预约到店状态",
    action: "办理顾客到店",
    entry: "店员 · 工作台",
    completion: "主预约的到店业务事件已记录。",
    nextAction: "切换店员并办理到店",
  },
  {
    role: "店员",
    object: "主预约使用状态",
    action: "开始使用预约座位",
    entry: "店员 · 工作台",
    completion: "主预约的开始使用业务事件已记录。",
    nextAction: "开始顾客使用",
  },
  {
    role: "顾客",
    object: "顾客商品订单",
    action: "创建并模拟支付订单",
    entry: "顾客 H5 · 我的订单",
    completion: "主预约关联订单的模拟支付成功事件存在。",
    nextAction: "切换顾客并创建、模拟支付订单",
  },
  {
    role: "店员",
    object: "顾客商品订单",
    action: "推进商品订单履约",
    entry: "店员 · 商品订单",
    completion: "店员已开始制作、标记待取或完成该已模拟支付订单。",
    nextAction: "切换店员并推进订单履约",
  },
  {
    role: "共享工具",
    object: "共享业务时钟",
    action: "推进共享业务时间",
    entry: "顶栏 · 业务时间",
    completion: "向前推进 30 分钟的审计事件已记录；真实 TTL 不变。",
    nextAction: "打开业务时间并推进 30 分钟",
  },
  {
    role: "顾客",
    object: "主预约关联报修",
    action: "提交耳机右声道无声报修",
    entry: "顾客 H5 · 我的报修",
    completion: "推进时间后已提交“耳机右声道无声”报修。",
    nextAction: "切换顾客并提交报修",
  },
  {
    role: "店员",
    object: "维修、库存流水与模拟退款",
    action: "处理维修、备件与结论",
    entry: "店员 · 报修",
    completion: "已分派、开始处理、领用替换耳机、记录模拟退款并提交维修结论。",
    nextAction: "切换店员并处理报修与备件",
  },
  {
    role: "店长",
    object: "维修复核、座位恢复与审计",
    action: "复核维修并查看经营证据",
    entry: "店长 · 报修 → 经营看板 / 审计与导出",
    completion: "独立复核通过，维修关闭、座位恢复可用并可读取同一证据。",
    nextAction: "切换店长，复核维修并读取经营证据",
  },
  {
    role: "总部运营",
    object: "固定三店看板与 CSV 导出",
    action: "比较三店并导出 CSV",
    entry: "总部运营 · 门店比较 → 审计与导出",
    completion: "同一总部请求为三家固定门店写入导出审计记录。",
    nextAction: "切换总部并比较固定三店",
  },
  {
    role: "共享工具",
    object: "独立三店演示世界",
    action: "重置为全新主演示",
    entry: "顶栏 · 重置演示数据",
    completion: "替换沙箱已创建，旧对象被拒绝且清单归零。",
    nextAction: "创建全新沙箱并重置清单",
  },
];

export const productCatalog = [
  ["零点气泡水", "饮品", "三店可用", "正常", "zero-sparkling-water", "清爽气泡饮品 · 冷藏取用"],
  ["脉冲能量饮料", "饮品", "三店可用", "正常", "pulse-energy-drink", "果味功能饮品 · 冷藏取用"],
  ["星澜果味水", "饮品", "旗舰店、标准店", "正常", "starlight-fruit-water", "低糖果味饮品 · 常温或冷藏"],
  ["折线薯片", "零食", "三店可用", "正常", "vector-crisps", "轻脆咸味零食 · 独立包装"],
  ["赛点能量棒", "零食", "旗舰店、标准店", "正常", "matchpoint-bar", "谷物能量棒 · 独立包装"],
  ["星光脆片", "零食", "旗舰店、新店", "正常", "starlight-crisp", "轻脆咸味零食 · 独立包装"],
  ["晨光鸡肉卷", "餐食", "旗舰店、标准店", "正常", "dawn-chicken-wrap", "加热即食餐食 · 虚构商品"],
  ["夜航饭团", "餐食", "标准店、新店", "正常", "night-rice-roll", "便携即食餐食 · 虚构商品"],
  ["回路咖啡", "饮品", "三店可用", "正常", "circuit-coffee", "轻焙咖啡饮品 · 冷藏取用"],
  ["外设清洁套装", "用品", "旗舰店、新店", "正常", "peripheral-cleaning-kit", "桌面与外设清洁用品"],
  ["一次性耳罩", "用品", "三店可用", "正常", "disposable-ear-covers", "公共耳机卫生用品"],
  ["清醒薄荷糖", "零食", "三店可用", "正常", "wake-mint", "小盒装无糖薄荷糖 · 独立包装"],
];

export const machineProfiles = [
  ["标准型", "1080p / 144Hz", "适合轻量竞技与日常体验", "86 个座位"],
  ["竞技型", "2K / 180Hz", "平衡画质与高刷新体验", "78 个座位"],
  ["旗舰型", "2K / 240Hz", "强调高刷新与沉浸体验", "36 个座位"],
];
