import { fileURLToPath } from "node:url";

import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import pg from "pg";

export * from "./schema.js";
export {
  AttendanceConflictError,
  type AttendanceConflictReason,
  HandoverConflictError,
  type HandoverConflictReason,
  CustomerOrderConflictError,
  type CustomerOrderConflictReason,
  CustomerSeatBrowseValidationError,
  type CustomerSeatBrowseValidationReason,
  CustomerReservationCreateConflictError,
  type CustomerReservationCreateConflictReason,
  CustomerReservationIdempotencyConflictError,
  CustomerReservationLifecycleConflictError,
  type CustomerReservationLifecycleConflictReason,
  FrontlineReservationConflictError,
  type FrontlineReservationConflictReason,
  StaffOrderConflictError,
  type StaffOrderConflictReason,
  ManagerInventoryConflictError,
  type ManagerInventoryConflictReason,
  ManagerDashboardRangeError,
  type ManagerDashboardRangeReason,
  ManagerStoreConfigurationConflictError,
  type ManagerStoreConfigurationConflictReason,
  ManagerPeopleConflictError,
  type ManagerPeopleConflictReason,
  RepairIntakeConflictError,
  type RepairIntakeConflictReason,
  RepairCommandConflictError,
  type RepairCommandConflictReason,
  RepairImageConflictError,
  type RepairImageConflictReason,
  DemoTimeAdvanceLimitReachedError,
  DemoTimeNoNextEventError,
  PublicSandboxIdempotencyConflictError,
  PublicSandboxOwnershipConflictError,
  RoleContextStaleError,
  RoleContextUnavailableError,
  SandboxCommandIdempotencyConflictError,
} from "./errors.js";
export {
  createPublicSandboxDatabase,
  type CancelCustomerReservationInput,
  type CancelCustomerOrderInput,
  type CreatePublicSandboxInput,
  type CreateCustomerPendingReservationInput,
  type CreateCustomerPendingOrderInput,
  type CreateCustomerRepairInput,
  type CreateStaffRepairInput,
  type CreateRepairImageIntentInput,
  type CreateRepairSampleImageInput,
  type ClaimRepairImageUploadInput,
  type CompleteRepairImageUploadInput,
  type CustomerBrowseContextInput,
  type DatabaseCustomerSeatAvailability,
  type DatabaseCustomerPendingReservation,
  type DatabaseCustomerJourney,
  type DatabaseCustomerOrderCancellation,
  type DatabaseCustomerOrderCatalog,
  type DatabaseCustomerOrderDetail,
  type DatabaseCustomerOrderPayment,
  type DatabaseCustomerPendingOrder,
  type DatabaseRepairCreated,
  type DatabaseRepairCommand,
  type DatabaseRepairSpareCommand,
  type DatabaseRepairSpareUsage,
  type DatabaseRepairResolutionCommand,
  type DatabaseRepairVerificationCommand,
  type DatabaseRepairDetail,
  type DatabaseStaffRepairIntake,
  type DatabaseStaffRepairQueue,
  type DatabaseRepairImage,
  type DatabaseRepairImageCleanupJob,
  type DatabaseRepairImageListItem,
  type DatabaseRepairImageIntent,
  type DatabaseRepairSampleImage,
  type DatabaseCustomerJourneyReservation,
  type DatabaseCustomerMembership,
  type DatabaseCustomerReservationCancellation,
  type DatabaseCustomerReservationDetail,
  type DatabaseCustomerReservationPayment,
  type DatabaseCustomerStoreCatalog,
  type DatabaseStaffReservationCommand,
  type DatabaseStaffReservationDetail,
  type DatabaseStaffReservationList,
  type DatabaseStaffReservationSummary,
  type DatabaseStaffReservationWorkbench,
  type DatabaseAttendanceCommand,
  type DatabaseOwnShiftAttendance,
  type DatabaseOwnHandovers,
  type DatabaseHandover,
  type DatabaseHandoverSnapshot,
  type DatabaseHandoverCommand,
  type DatabaseManagerHandoverExceptions,
  type DatabaseManagerStoreConfiguration,
  type DatabaseManagerStoreConfigurationCommand,
  type DatabaseManagerPeopleSchedule,
  type DatabaseManagerShiftPreview,
  type DatabaseManagerPeopleCommand,
  type DatabaseHeadquartersPeopleSchedule,
  type DatabaseStaffShift,
  type DatabaseStaffOrderCommand,
  type DatabaseStaffOrderDetail,
  type DatabaseStaffOrderQueue,
  type DatabaseStaffOrderSummary,
  type DatabaseManagerInventoryCommand,
  type DatabaseManagerDashboard,
  type ManagerDashboardDrilldownKind,
  type ReadManagerDashboardInput,
  type DatabaseStoreInventory,
  type DatabaseStoreInventoryItem,
  type DatabaseInventoryMovement,
  type DatabaseRoleContext,
  type PublicSandboxDatabase,
  type PublicSandboxDatabaseOptions,
  type PublicSandboxResult,
  type ExecuteStaffReservationCommandInput,
  type ExecuteOwnAttendanceCommandInput,
  type SubmitOwnHandoverInput,
  type ConfirmHandoverInput,
  type ExecuteStaffOrderCommandInput,
  type ExecuteManagerInventoryCommandInput,
  type EnqueueRepairImageCleanupInput,
  type FrontlineRole,
  type ReadCustomerSeatAvailabilityInput,
  type ReadCustomerReservationDetailInput,
  type ReadCustomerOrderCatalogInput,
  type ReadCustomerOrderDetailInput,
  type ReadStaffReservationDetailInput,
  type ReadStaffReservationListInput,
  type ReadStaffReservationWorkbenchInput,
  type ReadOwnShiftAttendanceInput,
  type ReadStaffRepairIntakeInput,
  type ReadRepairImageInput,
  type RepairStaffContextInput,
  type RepairActorContextInput,
  type ExecuteRepairCommandInput,
  type ExecuteRepairSpareCommandInput,
  type ExecuteRepairResolutionCommandInput,
  type ExecuteRepairVerificationCommandInput,
  type PrepareRepairImageCompletionInput,
  type FinalizeRepairImageInput,
  type FailRepairImageIntentInput,
  type ReadStaffOrderDetailInput,
  type ReadStaffOrderQueueInput,
  type ReadStoreInventoryInput,
  type ReadManagerStoreConfigurationInput,
  type ExecuteManagerStoreConfigurationCommandInput,
  type ReadManagerPeopleScheduleInput,
  type PreviewManagerShiftCoverageInput,
  type ExecuteManagerPeopleCommandInput,
  type ReadHeadquartersPeopleScheduleInput,
  type SimulateCustomerReservationPaymentInput,
  type SimulateCustomerOrderPaymentInput,
  type RecordRoleContextDenialInput,
  type ReadCurrentRoleContextInput,
  type ReadRoleContextInput,
  type SwitchRoleContextInput,
} from "./public-sandbox.js";
export {
  DEMO_TIME_DUE_HANDLER_ORDER,
  type AdvanceDemoTimeInput,
  type AdvanceDemoTimeResult,
  type DatabaseBusinessClock,
  type DatabaseDemoTimePreview,
  type DemoTimeDueHandler,
  type DemoTimeDueHandlerKind,
  type DemoTimeDueHandlerRegistry,
  type DemoTimeImpact,
  type DemoToolRoleContextInput,
  type ResetSandboxInput,
  type ResetSandboxOutcome,
  type ResetSandboxResult,
  type WallClock,
} from "./sandbox-demo-tools.js";

const { Pool } = pg;
const migrationsFolder = fileURLToPath(new URL("../drizzle", import.meta.url));

export async function migrateEmptyDatabase(databaseUrl: string): Promise<void> {
  const pool = new Pool({ connectionString: databaseUrl, max: 1 });

  try {
    await migrate(drizzle(pool), { migrationsFolder });
  } finally {
    await pool.end();
  }
}
